# Generated by Django 4.0.4 on 2022-06-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
